export const Persons = [
  {
    name: 'Rick Sanchez',
    gender: 'Male',
    species: 'Human',
    status: 'Alive',
    location: 'Citadel of Ricks',
    img: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
  },
  {
    name: 'Morty Smith',
    gender: 'Male',
    species: 'Human',
    status: 'Alive',
    location: 'Citadel of Ricks',
    img: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
  },
  {
    name: 'Jerry Smith',
    gender: 'Male',
    species: 'Human',
    status: 'Alive',
    location: 'Earth (Replacement Dimension)',
    img: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
  },
  {
    name: 'Summer Smith',
    gender: 'Female',
    species: 'Human',
    status: 'Alive',
    location: 'Earth (Replacement Dimension)',
    img: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
  },
  {
    name: 'Beth Smith',
    gender: 'Female',
    species: 'Human',
    status: 'Alive',
    location: 'Earth (Replacement Dimension)',
    img: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
  },
  {
    name: 'Abradolf Lincler',
    gender: 'Male',
    species: 'Human',
    status: 'unknown',
    location: 'Testicle Monster Dimension',
    img: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
  },
  {
    name: 'Adjudicator Rick',
    gender: 'Male',
    species: 'Human',
    status: 'Dead',
    location: 'Citadel of Ricks',
    img: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
  },
  {
    name: 'Alan Rails',
    gender: 'Female',
    species: 'Human',
    status: 'Dead',
    location: 'Worldender`s lair',
    img: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
  },
];
